@startuml d
class Владелец{
+ФИО
+Паспортные данные
+Документы на квартиру
Регистраия в системе()
Предоставить информацию о жилье()
Сдать жилье()
}

class Квартиросъемщик{
+ФИО
+Паспортные данные
+Справка о доходах
+Справка о судимости
Регистраия в системе()
Поиск жилья()
Снять жилье()
}

class Квартира{
+Адрес квартиры
+Номер этажа
+Номер квартиры
+Количество комнат
+Техника в квартире
}

class Аккаунт{
+Логин
+Пароль
+Номер телефона
+Верификация
}

Владелец ---> Аккаунт:Регистрирует акк
Квартиросъемщик --> Аккаунт:Регистрирует акк
Аккаунт ...> Квартира: Выставить и поиск 
Владелец ---> Квартира:Регистрирует в системе
Владелец ---> Квартира:Сдать жилье
Квартиросъемщик ---> Квартира: Снять жилье
@enduml