@startuml Inversion_Of_Control
class YourName.your_name {
- config []
+ def your_name()
}
class YourName.your_name_people {
+ def your_name_people()
}
class YourName.main {
- config []
+ def your_name()
}
class YourName.pavel {
+ people.append()
}


YourName.your_name <|.. YourName.main
YourName.your_name_people <|.. YourName.main
YourName.pavel <|.. YourName.your_name
@enduml