@startuml "Диаграмма последовательности"
participant Владелец
participant Квартиросъемщик
participant Агент

Владелец -> Агент: 1. Зарегистрироваться в системе
Квартиросъемщик -> Агент: 2. Зарегистрироваться в системе
Владелец -> Агент: 3. Предоставить информацию о жилье
Квартиросъемщик -> Агент: 4. Поиск жилья
Квартиросъемщик -> Владелец: 5. Снять жилье
Владелец -> Квартиросъемщик: 6. Сдать жилье

@enduml